// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DAL.Models;

public partial class Address
{
    public int AddressId { get; set; }

    public int AccountId { get; set; }

    public string AddressLine { get; set; } = null!;

    public string City { get; set; } = null!;

    public string? District { get; set; }

    public string? Ward { get; set; }

    public bool IsDefault { get; set; }

    public bool IsDeleted { get; set; }

    public string? RecipientName { get; set; }

    public string? PhoneNumber { get; set; }

    public int? ProvinceId { get; set; }

    public int? DistrictId { get; set; }

    public string? WardCode { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual Account Account { get; set; } = null!;
}