// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DAL.Models;

public partial class BackgroundJob
{
    public int JobId { get; set; }

    public string JobName { get; set; } = null!;

    public string? CronExpression { get; set; }

    public bool IsEnabled { get; set; }

    public DateTime? LastRunTime { get; set; }

    public DateTime? NextRunTime { get; set; }

    public string? LastRunStatus { get; set; }

    public string? LastRunMessage { get; set; }

    public virtual ICollection<Delivery> Deliveries { get; set; } = new List<Delivery>();
}