// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DAL.Models;

public partial class ExternalApiLog
{
    public long LogId { get; set; }

    public string Provider { get; set; } = null!;

    public string? Endpoint { get; set; }

    public string? Method { get; set; }

    public string? RequestPayload { get; set; }

    public string? ResponsePayload { get; set; }

    public int? StatusCode { get; set; }

    public DateTime CreatedAt { get; set; }

    public int? CreatedBy { get; set; }
}