// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DAL.Models;

public partial class PaymentGatewayTransaction
{
    public long GatewayTransactionId { get; set; }

    public long PaymentHistoryId { get; set; }

    public string Provider { get; set; } = null!;

    public string? TransactionId { get; set; }

    public string? PaymentUrl { get; set; }

    public string Status { get; set; } = null!;

    public decimal Amount { get; set; }

    public string? GatewayResponse { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? CompletedAt { get; set; }

    public virtual PaymentHistory PaymentHistory { get; set; } = null!;
}