// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DAL.Models;

public partial class ReviewModerationLog
{
    public int ModerationLogId { get; set; }

    public int ReviewProductId { get; set; }

    public string Stage { get; set; } = null!;

    public string Result { get; set; } = null!;

    public decimal? Score { get; set; }

    public string? Details { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual ReviewProduct ReviewProduct { get; set; } = null!;
}